name: ip_geolocation_io
description: Gets the geolocation with ipgeolocation.io API
version: 1.0.0
homepage: https://github.com/cedvdb/dart_ip_geolocation_io

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  http: ^0.13.4
