name: ip_geolocation_io
description: Gets the geolocation with ipgeolocation.io API
version: 1.1.0
homepage: https://github.com/cedvdb/dart_ip_geolocation_io

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  http: ^1.2.1
